version: '3'
services:
  app:
    image: dating-app-dev
    container_name: dating_app
    build:
      context: .
      args:
        - GROUP_NAME=${GROUP_NAME:-node}
        - GROUP_ID=${GROUP_ID:-1000}
        - USER_NAME=${USER_NAME:-node}
        - USER_ID=${USER_ID:-1000}
        - PORT=${PORT:-3000}
    ports:
      - ${PORT:-3000}:3000
      - ${PRISMA_STUDIO_PORT:-5555}:5555
    expose:
      - ${PORT:-3000}
      - ${PRISMA_STUDIO_PORT:-5555}
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules
