version: '3'
services:
  app:
    image: dating-app-dev
    container_name: dating_app
    build:
      context: .
      args:
        - GROUP_NAME=${GROUP_NAME:-node}
        - GROUP_ID=${GROUP_ID:-1000}
        - USER_NAME=${USER_NAME:-node}
        - USER_ID=${USER_ID:-1000}
        - PORT=${PORT:-3000}
    ports:
      - ${PORT:-3000}:3000
      - ${PRISMA_STUDIO_PORT:-5555}:5555
    expose:
      - ${PORT:-3000}
      - ${PRISMA_STUDIO_PORT:-5555}
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.5
    container_name: dating_app_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?}
      - POSTGRES_USER=${DB_USER?}
      - POSTGRES_DB=${DB_NAME:-app_db}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  