version: '3'
services:
  app:
    image: dating-app-dev
    container_name: app
    build:
      context: .
      args:
        - GROUP_NAME=${GROUP_NAME:-node}
        - GROUP_ID=${GROUP_ID:-1000}
        - USER_NAME=${USER_NAME:-node}
        - USER_ID=${USER_ID:-1000}
        - PORT=${PORT:-3000}
    ports:
      - ${PORT:-3000}:3000
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?}
      - MYSQL_DATABASE=${MYSQL_DATABASE?}
      - MYSQL_USER=${MYSQL_USER?}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH?}/node_modules
  mysql:
    driver: local
  