/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
      },
    },
    fontFamily: {
      serif: ['Overlock', 'ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      sans: [
        'Poppins',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
    },
    colors: ({ colors }) => ({
      primaryText: '#190109',
      primaryActive: '#F90657',
      primary: '#FA3D7C',
      primaryLight: '#FDB4CD',
      primaryLighter: '#FEE6EE',
      primaryLightest: '#FFFAFC',
      secondaryText: '#0D0119',
      secondaryActive: '#8006F9',
      secondary: '#9C3DFA',
      secondaryLight: '#D9B4FD',
      secondaryLighter: '#F2E6FE',
      white: '#FFFFFF',
      muted: '#7A525F',
      black: '#0A0003',
      border: '#C9B6BC',
      transparent: 'transparent',
      green: colors.green,
      red: colors.red,
    }),
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      black: 900,
    },
    fontSize: {
      h1: ['2.5rem', { lineHeight: '2.75rem' }],
      h2: ['2rem', { lineHeight: '2.25rem' }],
      h3: ['1.25rem', { lineHeight: '1.75rem' }],
      lg: ['1.125rem', { lineHeight: '1.75rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
    },
    ringColor: ({ theme }) => ({
      DEFAULT: theme('colors.primaryLight', '#F2E6FE'),
      ...theme('colors'),
    }),
    extend: {},
  },
  plugins: [],
};
