import type { NextPage } from 'next';
import Head from 'next/head';
import { Hero } from '../components/pages/hero/Hero';
import { Process } from '../components/pages/process/Process';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ditto: Online dating with privacy</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Hero />
      <Process />
    </>
  );
};

export default Home;
